<a href="https://colab.research.google.com/github/purvasingh96/pytorch-examples/blob/master/Basics/01.%20Deep_Learning_with_PyTorch_A_60_Minute_Blitz_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is PyTorch?
A scientific computing package that is -
* A replacement for NumPy to use the power of GPUs
* A deep learning research platform that provides maximum flexibility and speed
# Getting Started 
### Tensors

* Empty tensor gets initialized with random values allocated at run time.

In [0]:
from __future__ import print_function
import torch 

In [9]:
empty_tensor = torch.empty(5, 3)
zero_tensor = torch.zeros(5, 3, dtype=torch.long)
direct_tensor = torch.tensor([5, 5, 6, 8])
one_tensor = zero_tensor.new_ones(5, 3, dtype=torch.double)

print('Empty Tensor : \n', empty_tensor)
print('\n')
print('Zero Tensor : \n', zero_tensor)
print('\n')
print('Direct Tensor : \n', direct_tensor)
print('\n')
print('Ones Tensor : \n', one_tensor)

Empty Tensor : 
 tensor([[5.7450e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 1.6255e-43],
        [2.6194e+20, 1.6427e-07, 1.6595e-07],
        [2.1781e-04, 4.1723e-08, 6.7130e-07],
        [3.3090e+21, 3.4003e-06, 0.0000e+00]])


Zero Tensor : 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Direct Tensor : 
 tensor([5, 5, 6, 8])


Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
old_tensor = one_tensor
new_tensor = torch.rand_like(old_tensor, dtype=torch.float)

print('Size of new tensor : ', new_tensor.size())
print('\n')
print('Old tensor with overridden dType and same size as old_tensor : \n',new_tensor)

Size of new tensor :  torch.Size([5, 3])


Old tensor with overridden dType and same size as old_tensor : 
 tensor([[0.5932, 0.1361, 0.9276],
        [0.4668, 0.4190, 0.5359],
        [0.6300, 0.0740, 0.5790],
        [0.6140, 0.6834, 0.3323],
        [0.5462, 0.8163, 0.9566]])


### Operations


In [16]:
new_tensor = torch.rand(5, 3)
simple_addition = old_tensor + new_tensor
torch_add = torch.add(old_tensor, new_tensor)
output_tensor_as_argument = torch.empty(5, 3)
torch.add(old_tensor, new_tensor, out=output_tensor_as_argument)
inplace_addition = new_tensor.add_(old_tensor)

print('x + y : \n', simple_addition)
print('\n')
print('torch.add() : \n', torch_add)
print('\n')
print('Output tensor as argument : \n', output_tensor_as_argument)
print('\n')
print('In-place addition : \n', inplace_addition)

x + y : 
 tensor([[1.9855, 1.2796, 1.9305],
        [1.9259, 1.3387, 1.6248],
        [1.9437, 1.8683, 1.1107],
        [1.2303, 1.0151, 1.3394],
        [1.0631, 1.6831, 1.7090]], dtype=torch.float64)


torch.add() : 
 tensor([[1.9855, 1.2796, 1.9305],
        [1.9259, 1.3387, 1.6248],
        [1.9437, 1.8683, 1.1107],
        [1.2303, 1.0151, 1.3394],
        [1.0631, 1.6831, 1.7090]], dtype=torch.float64)


Output tensor as argument : 
 tensor([[1.9855, 1.2796, 1.9305],
        [1.9259, 1.3387, 1.6248],
        [1.9437, 1.8683, 1.1107],
        [1.2303, 1.0151, 1.3394],
        [1.0631, 1.6831, 1.7090]])


In-place addition : 
 tensor([[1.9855, 1.2796, 1.9305],
        [1.9259, 1.3387, 1.6248],
        [1.9437, 1.8683, 1.1107],
        [1.2303, 1.0151, 1.3394],
        [1.0631, 1.6831, 1.7090]])


### Indexing Tensors


In [17]:
print('Print first row : \n', new_tensor[:, 1])

Print first row : 
 tensor([1.2796, 1.3387, 1.8683, 1.0151, 1.6831])
